# Generated by Django 5.0 on 2025-02-19 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("SPANYAPP", "0003_alter_vouchers_expiration_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="vouchers",
            name="offer_description",
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="vouchers",
            name="sub_description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="vouchers",
            name="terms_and_conditions",
            field=models.TextField(blank=True, null=True),
        ),
    ]
