# Generated by Django 5.0 on 2025-02-22 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("SPANYAPP", "0006_paymentcards"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentcards",
            name="card_holder_name",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
