# Generated by Django 5.0 on 2025-03-10 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("SPANYAPP", "0007_paymentcards_card_holder_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="shippingaddress",
            name="customuser",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="SPANYAPP.customuser",
            ),
        ),
    ]
