# Generated by Django 5.0 on 2025-03-10 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("SPANYAPP", "0008_shippingaddress_customuser"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="shippingaddress",
            name="customuser",
        ),
        migrations.AddField(
            model_name="review",
            name="customuser",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="SPANYAPP.customuser",
            ),
        ),
    ]
