# Generated by Django 5.0 on 2025-03-11 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("SPANYAPP", "0009_remove_shippingaddress_customuser_review_customuser"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="voucher",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="SPANYAPP.vouchers",
            ),
        ),
    ]
