# Generated by Django 5.0 on 2025-03-11 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("SPANYAPP", "0010_order_voucher"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="ordertype",
            field=models.CharField(
                choices=[("Express", "Express"), ("Standard", "Standard")],
                default="Standard",
                max_length=20,
            ),
        ),
    ]
