# Generated by Django 5.0 on 2025-03-11 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("SPANYAPP", "0011_order_ordertype"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentcards",
            name="expiration_date",
            field=models.CharField(max_length=5),
        ),
    ]
