# Generated by Django 5.0 on 2025-03-11 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("SPANYAPP", "0012_alter_paymentcards_expiration_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="paymentcards",
            name="card_type",
        ),
    ]
